apiVersion: v1
kind: Service
metadata:
  name: semaphore-xds
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  labels:
    uw.systems/mirror: "true"
spec:
  type: ClusterIP
  ports:
    - name: xds
      port: 18000
      protocol: TCP
      targetPort: 18000
  selector:
    app.kubernetes.io/name: semaphore-xds
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: semaphore-xds
  labels:
    app.kubernetes.io/name: semaphore-xds
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: semaphore-xds
  template:
    metadata:
      labels:
        app.kubernetes.io/name: semaphore-xds
    spec:
      serviceAccountName: semaphore-xds
      containers:
        - name: xds-server
          image: semaphore-xds
          imagePullPolicy: Always
          ports:
            - containerPort: 18000
              protocol: TCP
