//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
The MIT License (MIT)

Copyright (c) 2022-2024 Utility Warehouse

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XdsService) DeepCopyInto(out *XdsService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XdsService.
func (in *XdsService) DeepCopy() *XdsService {
	if in == nil {
		return nil
	}
	out := new(XdsService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XdsService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XdsServiceList) DeepCopyInto(out *XdsServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]XdsService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XdsServiceList.
func (in *XdsServiceList) DeepCopy() *XdsServiceList {
	if in == nil {
		return nil
	}
	out := new(XdsServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XdsServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XdsServiceSpec) DeepCopyInto(out *XdsServiceSpec) {
	*out = *in
	if in.EnableRemoteEndpoints != nil {
		in, out := &in.EnableRemoteEndpoints, &out.EnableRemoteEndpoints
		*out = new(bool)
		**out = **in
	}
	in.LoadBalancing.DeepCopyInto(&out.LoadBalancing)
	if in.Retry != nil {
		in, out := &in.Retry, &out.Retry
		*out = new(XdsServiceSpecRetry)
		(*in).DeepCopyInto(*out)
	}
	out.Service = in.Service
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XdsServiceSpec.
func (in *XdsServiceSpec) DeepCopy() *XdsServiceSpec {
	if in == nil {
		return nil
	}
	out := new(XdsServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XdsServiceSpecLoadBalancing) DeepCopyInto(out *XdsServiceSpecLoadBalancing) {
	*out = *in
	if in.RingHash != nil {
		in, out := &in.RingHash, &out.RingHash
		*out = new(XdsServiceSpecLoadBalancingRingHash)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XdsServiceSpecLoadBalancing.
func (in *XdsServiceSpecLoadBalancing) DeepCopy() *XdsServiceSpecLoadBalancing {
	if in == nil {
		return nil
	}
	out := new(XdsServiceSpecLoadBalancing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XdsServiceSpecLoadBalancingRingHash) DeepCopyInto(out *XdsServiceSpecLoadBalancingRingHash) {
	*out = *in
	if in.MinimumRingSize != nil {
		in, out := &in.MinimumRingSize, &out.MinimumRingSize
		*out = new(uint64)
		**out = **in
	}
	if in.MaximumRingSize != nil {
		in, out := &in.MaximumRingSize, &out.MaximumRingSize
		*out = new(uint64)
		**out = **in
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XdsServiceSpecLoadBalancingRingHash.
func (in *XdsServiceSpecLoadBalancingRingHash) DeepCopy() *XdsServiceSpecLoadBalancingRingHash {
	if in == nil {
		return nil
	}
	out := new(XdsServiceSpecLoadBalancingRingHash)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XdsServiceSpecRetry) DeepCopyInto(out *XdsServiceSpecRetry) {
	*out = *in
	if in.RetryOn != nil {
		in, out := &in.RetryOn, &out.RetryOn
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NumRetries != nil {
		in, out := &in.NumRetries, &out.NumRetries
		*out = new(uint32)
		**out = **in
	}
	out.RetryBackOff = in.RetryBackOff
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XdsServiceSpecRetry.
func (in *XdsServiceSpecRetry) DeepCopy() *XdsServiceSpecRetry {
	if in == nil {
		return nil
	}
	out := new(XdsServiceSpecRetry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XdsServiceSpecRetryBackoffPolicy) DeepCopyInto(out *XdsServiceSpecRetryBackoffPolicy) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XdsServiceSpecRetryBackoffPolicy.
func (in *XdsServiceSpecRetryBackoffPolicy) DeepCopy() *XdsServiceSpecRetryBackoffPolicy {
	if in == nil {
		return nil
	}
	out := new(XdsServiceSpecRetryBackoffPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XdsServiceSpecService) DeepCopyInto(out *XdsServiceSpecService) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XdsServiceSpecService.
func (in *XdsServiceSpecService) DeepCopy() *XdsServiceSpecService {
	if in == nil {
		return nil
	}
	out := new(XdsServiceSpecService)
	in.DeepCopyInto(out)
	return out
}
