kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: semaphore-xds
rules:
  - apiGroups: [""]
    resources:
      - services
      - endpoints
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["discovery.k8s.io"]
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: semaphore-xds
subjects:
  - kind: ServiceAccount
    name: semaphore-xds
    namespace: sys-semaphore
roleRef:
  kind: ClusterRole
  name: semaphore-xds
  apiGroup: rbac.authorization.k8s.io
