apiVersion: v1
kind: Service
metadata:
  name: grpc-echo-server
  namespace: labs
  labels:
    xds.semaphore.uw.systems/enabled: "true"
spec:
  ports:
    - name: grpc
      port: 50051
  selector:
    app.kubernetes.io/name: grpc-echo-server
