apiVersion: semaphore-xds.uw.systems/v1alpha1
kind: XdsService
metadata:
  name: grpc-echo-server
  namespace: labs
spec:
  service:
    name: grpc-echo-server
  enableRemoteEndpoints: true
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-echo-server
  namespace: labs
spec:
  ports:
    - name: grpc
      port: 50051
  selector:
    app.kubernetes.io/name: grpc-echo-server
