name: build

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
  pull_request:
    branches:
      - "master"

env:
  REGISTRY: quay.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME_ENVOY_CONFIGURER: ${{ github.repository }}/envoy-sidecar/configurer

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Login to Quay.io Container Registry
        if: github.actor != 'dependabot[bot]'
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: utilitywarehouse+drone_ci
          password: ${{ secrets.SYSTEM_QUAY_TOKEN }}
      - name: Build and push Docker image
        if: github.actor != 'dependabot[bot]'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Extract envoy/configurer metadata (tags, labels) for Docker
        id: meta-envoy-configurer
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_ENVOY_CONFIGURER }}
      - name: Build and push Docker image for envoy configurer
        if: github.actor != 'dependabot[bot]'
        uses: docker/build-push-action@v5
        with:
          context: ./envoy-sidecar/configurer
          push: true
          tags: ${{ steps.meta-envoy-configurer.outputs.tags }}
          labels: ${{ steps.meta-envoy-configurer.outputs.labels }}
