name: Go
on:
  push:
jobs:
  mod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Tidy modules
        run: go mod tidy
      - name: Check for changes
        run: git add . && git diff --staged --exit-code
